Improve logic for updating configuration and restarting cjdroute

diff --git a/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns b/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
--- a/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
+++ b/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
@@ -2,22 +2,25 @@
 
 if [ -n $1 ];
 then
-    echo -n "Stopping cjdns interface $1... "
-    cat /var/run/cjdroute.$1.pid | xargs kill 2&>1
-    if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "OK."; else echo "failed."; fi
+    if [ `ps $1 | grep $1 | wc -l` -gt 0 ];
+    then
+        echo -n "Stopping cjdns interface $1... "
+        cat /var/run/cjdroute.$1.pid | xargs kill 2&>1
+        if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "OK."; else echo "failed."; fi
+    fi
 
     echo -n "Starting cjdns interface $1... "
     /opt/vyatta/sbin/cjdroute &>/var/log/cjdroute.$1.log < /config/cjdroute.$1.conf &
     if [ $? -eq 0 ]; then echo $! > /var/run/cjdroute.$1.pid; echo "OK."; else echo "failed."; fi
 else
-    if [ `pgrep cjdroute | wc -l` -ge 0 ];
+    if [ `pgrep cjdroute | wc -l` -gt 0 ];
     then
         echo -n "Stopping running cjdns interfaces... "
         cat /var/run/cjdroute.*.pid | xargs kill 2&>1
         if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "OK."; else echo "failed."; fi
     fi
 
-    if [ `ls cjdroute.*.conf | wc -l` -ge 0 ];
+    if [ `ls cjdroute.*.conf | wc -l` -gt 0 ];
     then
         ls cjdroute.*.conf | awk -v FS="(cjdroute.|.conf)" '{print $2}' | while read file;
         do
