Improved logic in vyatta-restart-cjdns

diff --git a/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns b/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
--- a/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
+++ b/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
@@ -1,8 +1,29 @@
 #!/bin/sh
 
-pgrep cjdroute | xargs kill 2&>1
+if [ -n $1 ];
+then
+    echo "Stopping cjdns interface $1... "
+    pgrep cjdroute.$1.conf | xargs kill 2&>1
+    if [ $? -eq 0 ]; then echo "OK."; else echo "failed."; fi
 
-ls cjdroute.*.conf | awk -v FS="(cjdroute.|.conf)" '{print $2}' | while read file;
-do
-    /opt/vyatta/sbin/cjdroute < /config/cjdroute.$file.conf;
-done
+    echo "Starting cjdns interface $1..."
+    /opt/vyatta/sbin/cjdroute < /config/cjdroute.$1.conf
+    if [ $? -eq 0 ]; then echo "OK."; else echo "failed."; fi
+else
+    if [ `pgrep cjdroute | wc -l` -ge 0 ];
+    then
+        echo "Stopping running cjdns interfaces... "
+        pgrep cjdroute | xargs kill 2&>1
+        if [ $? -eq 0 ]; then echo "OK."; else echo "failed."; fi
+    fi
+
+    if [ `ls cjdroute.*.conf | wc -l` -ge 0 ];
+    then
+        ls cjdroute.*.conf | awk -v FS="(cjdroute.|.conf)" '{print $2}' | while read file;
+        do
+            echo "Starting cjdns interface $file... "
+            /opt/vyatta/sbin/cjdroute < /config/cjdroute.$file.conf;
+            if [ $? -eq 0 ]; then echo "OK."; else echo "failed."; fi
+        done
+    fi
+fi
