Bug fixes

diff --git a/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns b/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
--- a/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
+++ b/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
@@ -6,21 +6,24 @@ then
     then
         echo -n "Stopping cjdns interface $1... "
         cat /var/run/cjdroute.$1.pid 2>/dev/null | xargs kill 2&>1
-        if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "OK."; else echo "failed."; fi
+        if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "OK.";
+        else rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "failed."; fi
     fi
 
     if [ `ls /config/cjdroute.*.conf 2>/dev/null | wc -l` -gt 0 ];
     then
         echo -n "Starting cjdns interface $1... "
         /opt/vyatta/sbin/cjdroute &>/var/log/cjdroute.$1.log < /config/cjdroute.$1.conf &
-        if [ $? -eq 0 ]; then echo $! > /var/run/cjdroute.$1.pid; echo "OK."; else echo "failed."; fi
+        if [ $? -eq 0 ]; then echo $! > /var/run/cjdroute.$1.pid; echo "OK.";
+        else rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "failed."; fi
     fi
 else
     if [ `pgrep cjdroute 2>/dev/null | wc -l` -gt 0 ];
     then
         echo -n "Stopping running cjdns interfaces... "
         cat /var/run/cjdroute.*.pid 2>/dev/null | xargs kill 2&>1
-        if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.*.pid &>/dev/null; echo "OK."; else echo "failed."; fi
+        if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.*.pid &>/dev/null; echo "OK.";
+        else rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "failed."; fi
     fi
 
     if [ `ls /config/cjdroute.*.conf 2>/dev/null | wc -l` -gt 0 ];
@@ -29,7 +32,8 @@ else
         do
             echo -n "Starting cjdns interface $file... "
             /opt/vyatta/sbin/cjdroute &>/var/log/cjdroute.$1.log < /config/cjdroute.$file.conf &
-            if [ $? -eq 0 ]; then echo $! > /var/run/cjdroute.$file.pid; echo "OK."; else echo "failed."; fi
+            if [ $? -eq 0 ]; then echo $! > /var/run/cjdroute.$file.pid; echo "OK.";
+            else rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "failed."; fi
         done
     fi
 fi
