Prevent cjdroute from being called when the config has been deleted

diff --git a/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns b/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
--- a/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
+++ b/vyatta-cjdns/opt/vyatta/sbin/vyatta-restart-cjdns
@@ -9,9 +9,12 @@ then
         if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "OK."; else echo "failed."; fi
     fi
 
-    echo -n "Starting cjdns interface $1... "
-    /opt/vyatta/sbin/cjdroute &>/var/log/cjdroute.$1.log < /config/cjdroute.$1.conf &
-    if [ $? -eq 0 ]; then echo $! > /var/run/cjdroute.$1.pid; echo "OK."; else echo "failed."; fi
+    if [ `ls /config/cjdroute.*.conf | wc -l` -gt 0 ];
+    then
+        echo -n "Starting cjdns interface $1... "
+        /opt/vyatta/sbin/cjdroute &>/var/log/cjdroute.$1.log < /config/cjdroute.$1.conf &
+        if [ $? -eq 0 ]; then echo $! > /var/run/cjdroute.$1.pid; echo "OK."; else echo "failed."; fi
+    fi
 else
     if [ `pgrep cjdroute | wc -l` -gt 0 ];
     then
@@ -20,9 +23,9 @@ else
         if [ $? -eq 0 ]; then rm -f /var/run/cjdroute.$1.pid &>/dev/null; echo "OK."; else echo "failed."; fi
     fi
 
-    if [ `ls cjdroute.*.conf | wc -l` -gt 0 ];
+    if [ `ls /config/cjdroute.*.conf | wc -l` -gt 0 ];
     then
-        ls cjdroute.*.conf | awk -v FS="(cjdroute.|.conf)" '{print $2}' | while read file;
+        ls /config/cjdroute.*.conf | awk -v FS="(cjdroute.|.conf)" '{print $2}' | while read file;
         do
             echo -n "Starting cjdns interface $file... "
             /opt/vyatta/sbin/cjdroute &>/var/log/cjdroute.$1.log < /config/cjdroute.$file.conf &
